### ISSUE TITLE
On Roster import, Hire Dates are loading in Assignment History, but not in First Employment Date

### ISSUE THREAD

**Issue by kenoshabrickk** [openoversightva/openoversight#117] opened 2023-09-30 21:23 UTC
I've tried this with a couple departments now after clearing the data a couple different ways & I think it might be a bug.

**Comment by kfinity** [comment] 2023-11-18 18:34
I think this is fixed now, I can't reproduce it.

**Closed by kfinity** 2023-11-18 18:34 UTC
Labels: bug
